//-----------------------------------------------------------------------
// <copyright file="d-timePicker">
	// * Copyright (C) 2019 Deng YinFeng All Rights Reserved
	// * email : 2537615635@qq.com
	// * version : 4.0.30319.42000
	// * author : auto generated by T4
	// * history : Created by T4 2019/10/31 10:28:31
	// </copyright>
//-----------------------------------------------------------------------

<template>
	<view v-show="state != -1" :class="state==1?'group toggle':'group toggle-exit'">
		<view class="util">
			<view style="color: #8F8F94;" @click="state = 0">取消</view>
			<view style="color: #008000;" @click="confim">确定</view>
		</view>
		<picker-view v-if="visible" style="height: 400upx;" :indicator-style="indicatorStyle" :value="value" @change="bindChange">
			<picker-view-column>
				<view class="item" v-for="(item,index) in years" :key="index">{{item}}年</view>
			</picker-view-column>
			<picker-view-column>
				<view class="item" v-for="(item,index) in months" :key="index">{{item}}月</view>
			</picker-view-column>
			<picker-view-column>
				<view class="item" v-for="(item,index) in days" :key="index">{{item}}日</view>
			</picker-view-column>
		</picker-view>
	</view>
</template>

<script lang="ts">
	import Vue from "vue";
	//装饰器
	import {
		Component,
		Emit,
		Inject,
		Model,
		Prop,
		Provide,
		Watch
	} from "vue-property-decorator";

	const date = new Date();
	const years: Array < number > = [];
	const year = date.getFullYear();
	const months: Array < number > = [];
	const month = date.getMonth() + 1;
	const days: Array < number > = [];
	const day = date.getDate();
	for (let i = 1990; i <= date.getFullYear(); i++) {
		years.push(i);
	}
	for (let i = 1; i <= 12; i++) {
		months.push(i);
	}
	for (let i = 1; i <= 31; i++) {
		days.push(i);
	}
	@Component({})
	export default class App extends Vue {
		title: string = "picker-view";
		years: Array < number > = years;
		year: number = year;
		months: Array < number > = months;
		month: number = month;
		days: Array < number > = days;
		day: number = day;
		value: Array < number > = [9999, this.month - 1, this.day - 1];
		visible: boolean = true;
		indicatorStyle: string = ``;

		//0关闭 1打开
		state: number = -1;

		bindChange(e: any) {
			const val = e.detail.value;
			this.year = this.years[val[0]];
			this.month = this.months[val[1]];
			this.day = this.days[val[2]];
		}

		open() {
			this.state = 1;
		}

		private close() {
			this.state = 0;
		}

		confim() {
			let time = [this.year, this.month, this.day];
			this.close();
			this.$emit("confim", time);
		}
	}
</script>

<style lang="scss" scoped>
	@import "./index.scss";
</style>
